services:
  backend:
    container_name: backend
    build: ./backend
    volumes:
      - /var/log/snort3/alert_json.txt:/build/alert_json.txt
    environment:
      - MQTT_BROKER=tcp://mosquitto:1883
    networks:
      - app-net
    restart: unless-stopped

  backend-dev:
    container_name: backend-dev
    build: ./backend
    ports:
      - 3001:3000
    volumes:
      - /var/log/snort3/alert_json.txt:/build/alert_json.txt
    environment:
      - MQTT_BROKER=tcp://mosquitto:1883
    networks:
      - app-net
    restart: unless-stopped

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 4000:4000
    environment:
      - VITE_BACKEND_HOST
      - VITE_ALLOWED_HOSTS
      - VITE_DESTINATION_COORDINATES=0,51.5
    networks:
      - app-net
    restart: unless-stopped
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - app-net
    restart: unless-stopped

networks:
  app-net:
    driver: bridge

