services:
  backend:
    container_name: backend
    build: ./backend
    # ports:
    #   - 3000:3000
    network_mode: host
    volumes:
      - /var/log/snort3/alert_json.txt:/build/alert_json.txt
      # networks:
      #   - app-net
    restart: unless-stopped
  backend-dev:
    container_name: backend-dev
    build: ./backend
    ports:
      - 3001:3000
    volumes:
      - /var/log/snort3/alert_json.txt:/build/alert_json.txt
      # networks:
      #   - app-net
    restart: unless-stopped

  frontend:
    container_name: frontend
    build: ./frontend
    develop:
      watch:
        - action: sync
          path: ./frontend/
          target: /build
          ignore:
            - node_modules/
    ports:
      - 4000:4000
    environment:
      - VITE_BACKEND_HOST
      - VITE_ALLOWED_HOSTS
      - VITE_DESTINATION_COORDINATES=0,51.5
    networks:
      - app-net
    restart: unless-stopped

networks:
  proxy-net:
    external: true
  app-net:
